ArduPilot/mavlink

message_definitions/v1.0/ardupilotmega.xml, message_definitions/v1.0/uAvionix.xml
MAVLink: add uAvionix as (first) vendor xml
This adds support for ADSB-out transceivers and sets us up for additional future vendors with reserved id space
=> MAVLink: add uAvionix as (first) vendor xml

message_definitions/v1.0/common.xml, pymavlink/mavutil.py
This PR includes two related changes:
- most importantly it has Peter Barker's new COLLISION message and associated enums.
- secondly it adds strings for recently added ArduPilot Copter flight modes
This PR is equivalent to this PR to upstream mavlink: https://github.com/mavlink/mavlink/pull/595
=> Peter Barker's new COLLISION message

message_definitions/v1.0/ardupilotmega.xml
The vehicle should send this command, with the requested position, to the GCS that started the accel calibration (the GCS must not answer this with a COMMAND_ACK). When the vehicle is in the requested position, the GCS will send the same command back to the vehicle with the requested position set (as a normal command it will be answered with a COMMAND_ACK).
=> Add command for accel calibration vehicle position

message_definitions/v1.0/ardupilotmega.xml, message_definitions/v1.0/common.xml, message_definitions/v1.0/minimal.xml
These where missing, and having them as an explicit attribute allows ground stations to display the data in a better way
=> Add missing enum attributes

message_definitions/v1.0/ardupilotmega.xml
This adds a new VISION_POSITION_DELTA mavlink message to the ArduPilot specific messages.
This message could probably be integrated into common.xml but there will be more developments related to adding SLAM support that might lead us to add more field to this message.  Because ArduPilot is the only user for the moment I think it's probably ok to leave it in the ardupilot specific set.
Here is a blog post explaining the setup including a video: http://discuss.ardupilot.org/t/ardupilot-openkai-zed-for-non-gps-navigation
=> ardupilot: add VISION_POSITION_DELTA message definition

message_definitions/v1.0/ardupilotmega.xml
Deprecates BATTERY2 in favour of BATTERY_STATUS. We will need to keep sending the message for awhile, but it's worth pointing users at the new messages.
=> ArduPilot: Deprecate BATTERY2 message

message_definitions/v1.0/ardupilotmega.xml, message_definitions/v1.0/common.xml, message_definitions/v1.0/uAvionix.xml
This removes the need for GCS to have hardcoded unit information
=> Add SI units

message_definitions/v1.0/common.xml
This is a suggested approach for bench testing motors in the same manner as baseflight or cleanflight. This is in order to resolve these issues: https://github.com/mavlink/qgroundcontrol/issues/3850 and https://github.com/mavlink/qgroundcontrol/issues/3710. Input from @lucasdemarchi and @LorenzMeier is welcomed and appreciated. I just want to get the ball rolling in this area.
=> Add MAV_CMD_DO_SET_MOTOR definition

message_definitions/v1.0/ardupilotmega.xml
I'm not sure how but the indexs used before were off by one, which resulted in float round off errors. I had tested this so I'm not sure how I had stuffed up the submitted PR...
=> ArduPilot: Correct an off by 1 error on accel cal reporting

message_definitions/v1.0/ardupilotmega.xml
This PR does the following:
- adds a new DO_WINCH command for use within a mission-item, command-long or command-int message to support controlling a winch for lowering packages from a vehicle
- changes the order in which the MAV_CMD_GIMBAL_RESET and MAV_CMD_SET_FACTORY_TEST_MODE commands appear in ardupilotmega.xml so that the order is consistent with the command-id value.  This is a non-functional change.
=> ardupilot: add DO_WINCH command

message_definitions/v1.0/ardupilotmega.xml
This maps out all currently supported flight modes that are reported via the `custom_mode` field of heartbeat.
=> Add a mapping of ArduPilot custom flight modes

message_definitions/v1.0/ardupilotmega.xml
It would be highly valuable to expose this information to the GCS, as it's one of the better indicators of a failing airspeed system.
=> ArduPilot: Add airspeed variance to EKF_STATUS_REPORT

message_definitions/v1.0/ardupilotmega.xml
This adds the enum value for the new Rover loiter mode.  Main ardupilot PR is here: https://github.com/ArduPilot/ardupilot/pull/8286
thanks to @peterbarker for reminding me I need to do this as part of adding a new flight mode.  I'll add this to our developer wiki pages on the subject.
=> ardupilotmega: add rover loiter mode

message_definitions/v1.0/ardupilotmega.xml
mavlink/mavlink updated to our orientation values, so we can tag this with the correct enum now (we still need to pull the change into our repo as well), which should help GCS's create reasonable UI's. This also fixes a copy paste error in the description of `new_orientation`
=> Tag MAG_CAL_REPORT orientation values

message_definitions/v1.0/common.xml
This MAVLink v2 packet allows for flexible obstacle detection from multiple sensors of varying resolution while still being backwards compatible.
increment_f (to override increment):
When forced to send exactly 72 samples, having an integer spacing just didn't make sense. Needed to be float so that the correct angular range was understood
angle_offset:
Same as, and adds to, param "[PRX_YAW_CORR](http://ardupilot.org/rover/docs/parameters.html#prx-yaw-corr-proximity-sensor-yaw-correction)". However, if you have two sensors you can send multiple messages covering different areas (at varying resolutions). For example, a 360 degree spinning lidar + long-range forward radar/lidar + wide angle sonar(s). With multiple messages, we can aggregate a better picture and down-scale the resolution to …
=> OBSTACLE_DISTANCE: add higher angle resolution and angle offset

message_definitions/v1.0/common.xml
to allow for SERIAL_CONTROL of any port
=> ardupilot: added SERIAL_CONTROL_SERIALn enums

message_definitions/v1.0/ardupilotmega.xml
this allows for fast compass calibration using just the known yaw of
the vehicle. This is ideal for large vehicles, if the user is able to
place the vehicle in a location without significant field distortions
=> ardupilot: added MAV_CMD_FIXED_MAG_CAL_YAW

message_definitions/v1.0/common.xml
this allows moving baseline GPS configurations to show their yaw
solution to the GCS. It also allows a GCS to display a warning if the
GPS is configured to provide yaw (eg. configured as a moving baseline
rover) and currently cannot provide yaw
=> common: added extension for GPS_RAW_INT and GPS2_RAW for yaw

message_definitions/v1.0/ardupilotmega.xml
These are needed for the EMU ECU:
https://github.com/ArduPilot/ardupilot/pull/12874
=> ardupilot: added more EFI status variables

message_definitions/v1.0/common.xml
This moves the fence status message from ardupilotmega to common inline with malink master. It also adds a extension to report fence mitigation action, This is any action being take by Autopilot to prevent a fence breach. ie stop or slide. This brings the message up-to date with mavlink master. 
https://github.com/mavlink/mavlink/pull/1215
=> extend FENCE_STATUS to report mitigation action, inline with mavlink master

message_definitions/v1.0/ardupilotmega.xml
alternative for  https://github.com/ArduPilot/mavlink/pull/124
https://github.com/ArduPilot/ardupilot/pull/13457
For the purpose of reporting initializing AHRS rather than bad on boot.
=> ardupilotmega: add initialized bit to EKF_STATUS_FLAGS

message_definitions/v1.0/ardupilotmega.xml
Extending the `SCRIPTING_CMD` enum would give us an easy way to restart scripts for example. This is also needed for https://github.com/ArduPilot/ardupilot/pull/13547
=> Add scripting MAVLink commands

message_definitions/v1.0/ardupilotmega.xml
These are definitely not "coming soon".  Or ever.
=> ardupilotmega.xml: remove ancient, commented out message definitions

message_definitions/v1.0/ardupilotmega.xml
This removes the units from the PID tuning message as we never abide by them anyway
https://github.com/ArduPilot/ardupilot/pull/14382
=> ardupilotmega: remove PID_TUNING units

message_definitions/v1.0/common.xml
A possible method for returning the airspeed temperature along with the baro temp. @WickedShell 
https://github.com/ArduPilot/ardupilot/pull/14852
=> common: send temp for abs and diff press

message_definitions/v1.0/common.xml
This PR adds a new WINCH_STATUS message for use with the Daiwa winch.  https://ardupilot.org/copter/docs/common-daiwa-winch.html
I have a PR which will improve AP's driver to make use of the telemetry connection from the winch and send it to the ground station using this message.
I plan to raise this against upstream mavlink as well.
All feedback welcome!
=> Common: add WINCH_STATUS message

message_definitions/v1.0/ardupilotmega.xml
This is a WIP.
This PR adds the ability to send obstacle distance message, in body frame from a 3-D depth camera. 
We assume the field of view is divided in a 3x3 grid like such:
We take the closest distance in each individual box, pack it into a NEU frame distance vector in meters and send it.
Furthermore, this message also includes an "ID" field for future implementation of detecting obstacles and tagging them with a  unique ID.
=> Ardupilotmega: add OBSTACLE_DISTANCE_3D message

message_definitions/v1.0/common.xml, message_definitions/v1.0/minimal.xml
I feel like this is a step in the right direction deprecating a lot of messages in favor of a much simpler protocol.
let the discussions begin
=> Deprecate MAV_CMD_REQUEST_* in favor of MAV_CMD_REQUEST_MESSAGE (#1180)

message_definitions/v1.0/common.xml
> Mark COMMAND_INT.current as not used. (mavlink#1514)
@hamishwillee and @peterbarker seam to disagree on this one
=> Sync to upstream 2020-12-07 - controversial patches

CMakeLists.txt, component_information/parameter.schema.json, message_definitions/v1.0/common.xml
> common.xml: Mark HIGH_LATENCY as deprecated by HIGH_LATENCY2 (mavlink#1505)
According to git grep and https://github.com/ArduPilot/ardupilot/issues/7341 none of these are implemented in ArduPilot yet. So OK to deprecate one.
> component_information: fix parameter.schema.json array type (mavlink#1519)
looks good to me
> common.xml: Add 'Inclusion Group' to fence for 'OR' fences (mavlink#1510)
@IamPete1 submitted this one upstream in mavlink#1510
>  CMake: Using find_program to find mavgen(.py) (mavlink#1485)
looks good to me
=> Sync to upstream 2020-12-09

message_definitions/v1.0/common.xml
> COMMAND_INT.autocontinue - clarify not used (mavlink#1309)
@hamishwillee has checked that it is not used in ArduPilot
This was part of #167
@peterbarker commented there:
> I have concerns about the autocontinue flag.
> It is referenced in several other places, including rather dramatically in the MISSION_ITEM description. Saying the attribute is unused when it is clearly referenced in several other places isn't good.
> I also have concerns that we may be ignoring other implementers of the mavlink standard by blowing away the attribute. I'd be a lot more comfortable if we had a registered list of interested parties in the standard.
=> common.xml: COMMAND_INT.autocontinue - clarify not used (#1309)

message_definitions/v1.0/ardupilotmega.xml
Adds a command for use in missions to trigger scripting actions
We could potentially use all 7 params, I didn't want to confuse matters with the different types.
Or we could include a location
=> ardupilotmega.xml: add MAV_CMD_DO_SEND_SCRIPT_MESSAGE

message_definitions/v1.0/common.xml
Add smart_battery_info message.
One small documentation change on the MAVLink side here: https://github.com/mavlink/mavlink/pull/1551
=> common.xml: add smart_battery_info message

message_definitions/v1.0/ardupilotmega.xml
This adds a water-depth message so that an underwater sonar's depth and temperature can be transmitted to the ground station in real-time.  We do already have an existing DISTANCE_SENSOR message that can be used but this is actually more like a camera feedback message in that it provides the lat, lon, attitude and temperature information as well which is important for producing a good quality 3D map.
The corresponding vehicle code PR to use this message is here https://github.com/ArduPilot/ardupilot/pull/17804
=> ardupilotmega.xml: add WATER_DEPTH

message_definitions/v1.0/common.xml
Add new MAV_CMD_DO_ADSB_OUT_IDENT to trigger an ADSB/ModeA/C/S Transponder IDENT.
The number 10001 was chosen because the uAvionix.xml file uses 10000-10099 but there's no MAV_CMDs in there. This was originally in that file but I pulled it out to common.xml. I think the same number is still OK to use though since it's not a msg_id.
=> add MAV_CMD_DO_ADSB_OUT_IDENT

message_definitions/v1.0/ardupilotmega.xml
This command allows an external system to set the EKF sensor source.  Instead of individually specifying which sensor should be used, the caller selects from 3 pre-defined (but configurable) sets (aka groups)
I think the only question is whether we want the mavlink command to accept the source set in the range 1 to 3 (to match the EK3_SRCx_ parameters) or 0 to 2 (to match the ahrs interface). Currently it is implemented in the 1 to 3 range.
ArduPilot GPS/Non-GPS Transitions wiki page: https://ardupilot.org/copter/docs/common-non-gps-to-gps.html
=> ardupilotmega: add MAV_CMD_SET_EKF_SOURCE_SET

message_definitions/v1.0/common.xml
This adds param_ext messages from upstream, as a step towards improving camera and gimbal support.  No intent for ArduPilot to support these messages, just parse them for routing.
Some cleanups are included: descriptions are updated to improve alignment, and WIP tags removed from now-stable messages.
=> Common.xml: add param_ext

message_definitions/v1.0/common.xml
This pulls down from mavlink/mavlink 2 messages (and associated enum) from the Gimbal V2 protocol:
GIMBAL_DEVICE_INFORMATION and AUTOPILOT_STATE_FOR_GIMBAL_DEVICE; and two extensions for STORAGE_INFORMATION, used by latest STorM32.  I have removed WIP tags from these messages.
ref: https://github.com/ArduPilot/mavlink/commit/f171b3fa8ec933039e2f16c24136c8858ea5a3ce#commitcomment-55121678 and https://github.com/mavlink/mavlink/issues/1669#issuecomment-899999622
This completes this iteration on common.xml.  Further discussion and analysis is needed prior to bringing in the complete gimbal v2 message set or the component_information service.
=> common.xml: Improve support for latest STorM32

message_definitions/v1.0/ardupilotmega.xml
used for H7 MCU monitoring. MCU temperature is useful for overheating, and the voltage range gives us an idea of how stable the power supply is
=> ardupilot: added MCU_STATUS message

message_definitions/v1.0/ardupilotmega.xml
this allows for scripts that execute arbitrary navigation commands
before handing back control
link to related flight code PR: https://github.com/ArduPilot/ardupilot/pull/19039
=> ardupilot: added NAV_SCRIPT_TIME mission item

message_definitions/v1.0/common.xml
Enums PARAM_ACK and MAV_PARAM_EXT_TYPE are never defined in ardupilot/mavlink.
```
<message id="324" name="PARAM_EXT_ACK">
<description>Response from a PARAM_EXT_SET message.</description>
<field type="char[16]" name="param_id">Parameter id, terminated by NULL if blah blah blah...</field>
<field type="char[128]" name="param_value">Parameter value blah blah blah...</field>
<field type="uint8_t" name="param_type" enum="MAV_PARAM_EXT_TYPE">Parameter type.</field>
<field type="uint8_t" name="param_result" enum="PARAM_ACK">Result code.</field>
</message>
```    
However, they're defined in mavlink/mavlink ([here](https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml#L3648-L3662)) and ([here](https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/com …
=> port missing enums PARAM_ACK and MAV_PARAM_EXT_TYPE from mavlink/mavlink

message_definitions/v1.0/common.xml, message_definitions/v1.0/minimal.xml
this allows for CAN over mavlink, making working with CAN nodes easier and able to be done remotely if the mavlink connection has enough bandwidth
=> ardupilot: added MAV_CMD_CAN_FORWARD

message_definitions/v1.0/common.xml
MAVProxy doesn't use this.
MissionPlanner doesn't use this.
QGroundControl doesn't use this
PX4Firmware doesn't use this.
The command equivalent, MAV_CMD_DO_SET_HOME allows for the command to be
rejected, so everyone can save flash by removing support for this
message.
=> common.xml: deprecate SET_HOME_POSITION message

message_definitions/v1.0/common.xml
these allow for filtering of CAN frames on the flight controller, which will allow for management of DroneCAN nodes over slow mavlink connections, such as SiK radios, even with a high CAN packet rate
also adds CANFD_FRAME for upcoming CANFD support
note: not tested yet, don't merge yet
=> added CANFD_FRAME and CAN_FILTER_MODIFY messages

message_definitions/v1.0/AVSSUAS.xml, message_definitions/v1.0/storm32.xml, message_definitions/v1.0/uAvionix.xml
AVSUAS and storm32 I've just pulled in as-is from upstream.
Our uavionix seems to have message definitions in it which aren't upstream, @magicrub @amilcarlucas
=> message_definitions: update message definitions from upstream

message_definitions/v1.0/common.xml
Add Radius to CMD_DO_REPOSIITON for better atomic operations of control on guided commands. It uses language from the other CMD_NAV_LOITER commands
=> Add radius to DO_REPOSITION

message_definitions/v1.0/ardupilotmega.xml
This adds a new ardupilot specific NAV_ATTITUDE_TIME command which allows the user to specify during a mission what attitude they would like the vehicle to maintain for a specified period of time.
PR https://github.com/ArduPilot/ardupilot/pull/20851 adds support for this message to Copter
This has been tested in SITL although this uncovered an [existing issue with MAVProxy and Mission Planner](https://github.com/ArduPilot/MissionPlanner/issues/2871) in how they always scale the 5th argument ("param5" or "x")
=> ardupilotmega: add nav_attitude_time command

message_definitions/v1.0/common.xml
This PR adds three messages and their accompanying enums from upstream:
- MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW <-- mission command (or immediate command) to set pitch and yaw of a gimbal
- GIMBAL_DEVICE_SET_ATTITUDE <-- command from autopilot to gimbal to move to a specified angle (or rate)
- GIMBAL_DEVICE_ATTITUDE_STATUS <-- message from gimbal including current angles and rates
These messages are required for a new AP_Mount library that improves our Gremsy gimbal support.  I have been actively using these messages in development.
=> common: add gimbal messages from upstream

message_definitions/v1.0/ardupilotmega.xml
The note might need some work...
Also the deprecated field really should accept versions too.  As version is more important than date both for a user and for us when removing things. 
This field was removed in Copter-4.2
=> ArduPilot: SENSOR_OFFSETS add deprecated note

message_definitions/v1.0/common.xml
this is required for the pre-arm check that the transmitter is ready
and passing tests
message ID chosen so as not to conflict with PR #1865
=> common: added OPEN_DRONE_ID_ARM_STATUS

message_definitions/v1.0/common.xml
this is a bandwidth efficient way to update the OPEN_DRONE_ID_SYSTEM
message data when there is limited uplink bandwidth. Testing on real
vehicles shows that with RFD900x radios at an air data rate of
125kbit/s with OPEN_DRONE_ID messages with 1Hz update (as required by
FAA RemoteID standard) that there is significant impact on the ability
of the GCS to give commands to the flight controller. For example, I
got a high degree of packet loss in downloading parameter pre-flight,
and many/most in-flight commands failed from the GCS.
By using this message we can use the minimum required bandwidth for
updating operator location while remaining FAA RemoteID standard
compliant
=> common: added OPEN_DRONE_ID_SYSTEM_UPDATE message

message_definitions/v1.0/common.xml
makes it possible to graph as an array
SERVO_OUTPUT_RAW[1].servo2_raw
=> common: set SERVO_OUTPUT_RAW.port as an instance to assist GCS

message_definitions/v1.0/all.xml, message_definitions/v1.0/ardupilotmega.xml, message_definitions/v1.0/cubepilot.xml
These are some custom message sets that CubePilot have been using internally. Adding them to master will help streamline things for us.
=> add vendor specs for cubepilot

message_definitions/v1.0/development.xml
Port of https://github.com/mavlink/mavlink/pull/1900 adding new airspeed message with the goal of more complete support of multiple sensors.
=> Development: update airspeed message

message_definitions/v1.0/common.xml
Add support for reporting fuel pressure in the `EFI_STATUS` message. Fuel pressure is already measured and logged by multiple EFI backends, and it can be a useful measurement to report to the GCS for diagnosing problems on the ground.
kPa chosen as the unit to match the two other pressure fields in the message, though this is a departure from other pressure fields in other messages.
We could potentially add other missing fields at this time too, but this one is the most useful.
=> common.xml: add fuel_pressure ext. to EFI_STATUS

message_definitions/v1.0/common.xml
Add missing MAV_ODID_STATUS entry.
- Remote ID System Failure
- Value 4
- Defined here: https://mavlink.io/en/messages/common.html#MAV_ODID_STATUS_REMOTE_ID_SYSTEM_FAILURE
Fixes issue #299
=> common.xml: add remote id system failure to MAV_ODID_STATUS

message_definitions/v1.0/common.xml
- MAV_ODID_GOOD_TO_ARM message have changed in the official mavlink repository some time ago in this PR https://github.com/mavlink/mavlink/pull/1883
- this was also raised in this ArduRemoteID issue https://github.com/ArduPilot/ArduRemoteID/issues/35
- other PRs will be submitted for ArduRemoteID and ArduPilot to allow the move to the new ENUMs.
=> use latest mavlink definitions for MAV_ODID_ARM_STATUS

message_definitions/v1.0/common.xml
This adds commands from upstream to set camera zoom and focus and related enums:
- MAV_CMD_SET_CAMERA_ZOOM and CAMERA_ZOOM_TYPE enum
- MAV_CMD_SET_CAMERA_FOCUS and SET_FOCUS_TYPE
.. and also camera tracking messages and enums which I hope to implement in the future
- MAV_CMD_CAMERA_TRACK_POINT
- MAV_CMD_CAMERA_TRACK_RECTANGLE
- MAV_CMD_CAMERA_STOP_TRACKING
- CAMERA_FOV_STATUS
- CAMERA_TRACKING_IMAGE_STATUS
- CAMERA_TRACKING_GEO_STATUS
- CAMERA_TRACKING_STATUS_FLAGS enum
- CAMERA_TRACKING_MODE enum
- CAMERA_TRACKING_TARGET_DATA enum
These are required for implementation of the [new MAVLink camera controls](https://mavlink.io/en/services/camera.html) used by cameras including the Gremsy ZIO.
=> common: add set camera zoom and focus

message_definitions/v1.0/common.xml
This starts off looking very much like MAV_RESULT but then starts to differ
Based off the name, remove this entirely so implementers are forced to move to MAV_RESULT.
For reference, here's MAV_RESULT, which is what CMD_ACK actually uses as an enumeration for its value field:
```
<enum name="MAV_RESULT">
<description>Result from a MAVLink command (MAV_CMD)</description>
<entry value="0" name="MAV_RESULT_ACCEPTED">
<description>Command is valid (is supported and has valid parameters), and was executed.</description>
</entry>
<entry value="1" name="MAV_RESULT_TEMPORARILY_REJECTED">
<description>Command is valid, but cannot be executed at this time. This is used to indicate a problem that should be fixed just by waiting (e.g. a state machine is busy, can't arm because have not got GPS lock, …
```
=> common.xml: remove MAV_CMD_ACK

message_definitions/v1.0/common.xml
This adds the GIMBAL_MANAGER_INFORMATION message and related GIMBAL_MANAGER_CAP_FLAGS enum/bitmask from the upstream mavlink repo.  This message is required so AP can better integrate with the upcoming QGC gimbal control screen (see PR: https://github.com/mavlink/qgroundcontrol/pull/10667)
- GIMBAL_MANAGER_INFORMATION sends capabilities flags and maximum lean angles to the GCS.
- GIMBAL_MANAGER_CAP_FLAGS is an enum / bitmask of all gimbal manager capabilities
I've also added the GIMBAL_MANAGER_STATUS which allows de-conflicting who/what is controlling the gimbal.  It's not yet clear if AP will need to add support for this message as well.
=> common: add gimbal-manager-information and cap-flags

message_definitions/v1.0/common.xml
Needed for the upcoming work in QGC:
https://github.com/mavlink/qgroundcontrol/pull/10667#issuecomment-1520733823
and related to this commit in AP:
https://github.com/ArduPilot/ardupilot/pull/23713
=> common.xml: add MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE

message_definitions/v1.0/common.xml
This adds the ODOMETRY quality field which is sent by the [ModalAI VOXL cameras](https://ardupilot.org/copter/docs/common-modalai-voxl.html).
Simply having this field visible in the GCS's mavlink inspectors will allow users to more easily see the quality without using ModalAI's built-in web application (which requires using a separate Wifi connection).  This also allows us to add better AP support for the camera's loss of position estimate.  As a minimum we will be able to:
1. Log the quality which will aid with support
2. refuse to fuse the position and velocity unless the quality value is above some threshold (perhaps 10%)
This has been lightly tested to confirm that AP can extract the quality field from the ODOMETRY message and that it compiles OK.
This commit is pulled directly from …
=> common: ODOMETRY add optional quality field

message_definitions/v1.0/common.xml
Lots of them are not WIP anymore, and some important fields were added to some messages, like gimbal_device_id. I am preparing the matching PR for Ardupilot.
@rmackay9 could be interested on this one.
I am marking it as draft until the matching PR is ready for AP as well.
=> Update gimbal manager v2 messages:

message_definitions/v1.0/all.xml, message_definitions/v1.0/ardupilotmega.xml, message_definitions/v1.0/csAirLink.xml
Hi. I am adding the ability to connect ground stations with Qgroundcontrol and MissionPlanner software to [AirLink lte modules](https://ardupilot.org/plane/docs/common-airlink-telemetry.html). Adding changes to master will help speed up the work.
=> Air-Link: Added messages for connections to air-link modules

message_definitions/v1.0/ardupilotmega.xml, message_definitions/v1.0/common.xml
Cherry-picked from upstream
I've reverted the description change as another patch; I don't know whether we actually honour that description in ArduPilot.  We may persist this across mode changes, I haven't checked.
=> Move SPEED_TYPE enumeration to common.xml, use it in DO_CHANGE_SPEED

message_definitions/v1.0/common.xml
Allow flagging that the engine should be started once while disarmed, also allows us to add further engine options in a bitfield. Intended for use in [#25138](https://github.com/ArduPilot/ardupilot/pull/25138)
=> Add ENGINE_CONTROL_OPTIONS

message_definitions/v1.0/common.xml
This pulls the upstream changes to CONDITION_YAW into the AP repo.  See upstream PR https://github.com/mavlink/mavlink/pull/2058
There is a small related AP flight code change here https://github.com/ArduPilot/ardupilot/pull/25646
This has been tested in SITL and seems fine.
=> MAV_CMD_CONDITION_YAW - shortest direction v2

message_definitions/v1.0/common.xml
decoding the old MODE message is a terrible way to do this
=> common.xml: add a command to deal with safety switch

message_definitions/v1.0/common.xml
Allows a bitmask to be passed to the fence enable function to specify individual fences to enable or disable
This has been done so that by not providing the second arg you get the current behaviour which is to enable and disable all fences
=> Allow individual fences to be enabled and disabled

message_definitions/v1.0/ardupilotmega.xml
Updates the flags enum in line with https://github.com/ArduPilot/ardupilot/pull/25380
=> ardupilotmega: add alt frame to RALLY_FLAGS enum

message_definitions/v1.0/development.xml
Already merged in the official MAVLink repository: https://github.com/mavlink/mavlink/pull/2082
=> development: MAV_CMD_DO_SET_SYS_CMP_ID: Add first version

message_definitions/v1.0/common.xml
This adds a mavlink command to change the active camera lens (e.g. which camera lens is being streamed to the GCS).  This is useful for cameras with multiple lenses like the ViewPro and Xacti cameras.
This has already been merged upstream albeit after much discussion. https://github.com/mavlink/mavlink/pull/2079
This also includes the unused mavlink command MAV_CMD_SET_STORAGE_USAGE which AP doesn't use but is directly above this new command in common.xml.
=> common: add set-camera-source command

message_definitions/v1.0/common.xml
the frame of an altitude is not dependent on how the altitude is being transported (how other fields in the same message are being transported).
ArduPilot has treated these frames to be the same as the non-_INT equivalents in most places for a very long time.
We can save some confusion and perhaps a small amount of flash space if we remove the _INT frames
Upstream PR is here: https://github.com/mavlink/mavlink/pull/2092
=> common.xml: deprecate the _INT frames

message_definitions/v1.0/common.xml
This adds a new waypoint type, to allow rejoing missions in a RTL. 
~https://github.com/ArduPilot/ardupilot/pull/18004~ https://github.com/ArduPilot/ardupilot/pull/26383
https://youtu.be/SoHXRTD0vEs
=> Common: add MAV_CMD_DO_LAND_REJOIN

message_definitions/v1.0/common.xml
Cameras that support H.265 are becoming more common. We need a way to specify the encoding of the video stream.
As per this PR: https://github.com/mavlink/mavlink/pull/2127
=> common.xml: Add "encoding" field to VIDEO_STREAM_INFORMATION

message_definitions/v1.0/development.xml
Upstream PR was here: https://github.com/mavlink/mavlink/pull/2110
* gps: add status and resilience information
Add fields to report resilience and status information from GNSS receivers back to ground control stations for representation in the user interface.
* gps: separate GNSS integrity information
Move the changes to the `GPS_RAW_INT` message into a separate message that supports multiple GNSS receivers. Update the enum values to better support all GNSS receivers.
* gps(integrity): add RAIM info to `GNSS_INTEGRITY` message
* gps(integrity): change `GNSS_INTEGRITY` message `id` field to instanced
Change the `id` field on the `GNSS_INTEGRITY` message to make use of the instance support in the MAVLink schema.
* gps(integrity): move integrity message to `development.xml`
* …
=> gps: add status and integrity information (#2110)

message_definitions/v1.0/ardupilotmega.xml
Altitude rate of change is climb rate which is measured in m/s. See: https://github.com/ArduPilot/ardupilot/pull/27921
=> ardupilotmega: MAV_CMD_GUIDED_CHANGE_ALTITUDE: correct alt rate-of-change unit

message_definitions/v1.0/ardupilotmega.xml
we're currently using this value as "1<<15" in the code; this will let us fix that
https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp#L596
=> ardupilotmega.xml: add EKF_GPS_GLITCHING status flag

message_definitions/v1.0/common.xml
This is the AP version of this upstream PR https://github.com/mavlink/mavlink/pull/2145 which has already been merged
The flight code change that uses this message is here https://github.com/ArduPilot/ardupilot/pull/27915
This adds a new message to allow sending a thermal camera's min and max temperatures (including the location on the image) to the ground station in real time.  This is useful for search & rescue and firefighting applications because the ground station can overlay a rectangle over the hotspot along with its temperature
I've tried to make it consistent with other CAMERA messages including the tracking message in the hopes that that makes it easier to merge.  I've also included the camera_device_id field consistent with PR https://github.com/mavlink/mavlink/pull/2142
Over …
=> common: add camera-thermal-status

message_definitions/v1.0/common.xml
This is porting the existing messages from upstream common.xml into ArduPilot
https://mavlink.io/en/messages/common.html#TRAJECTORY_REPRESENTATION_WAYPOINTS
=> Add Trajectory msgs from upstream

message_definitions/v1.0/ardupilotmega.xml
This updates the mode enums for Copter, Plane, Tracker, Sub, and Rover. There were a few missing modes. I also added descriptions which give the mode name.
=> ardupilotmega: update flight modes

message_definitions/v1.0/ardupilotmega.xml, message_definitions/v1.0/uAvionix.xml
This removes the `display="bitmask"` attribute on fields that reference a bitmask enum from the ArduPilot-managed dialects. I believe that to be the entire included set:
All the enums that use this are marked up as bitmasks using `bitmask="true"`, so the information on the field is inferable. We're heading towards removing the bitmask indication on the field itself.
History here is that `display="bitmask"` was added on request of QGC to allow auto-generation of checkbox UI. We later decided that it was better to have on the enum, because that is the thing we know is a bitmask. 
However neither attribute is actually used in QGC or Mission Planner or MAVProxy. It might be used elsewhere, but unlikely.
Upstream removes them in https://github.com/mavlink/mavlink/pull/2215
This falls out of …
=> Remove legacy attribute: display="bitmask"

message_definitions/v1.0/common.xml
From the original PR:
```
I'm proposing to change the unit of DO_REPOSITION param4, which is used for the yaw setpoint for multirotors.
Currently, the spec specifies degrees, however, PX4 implements it as radians, and so does MAVSDK.
ArduPilot seems to ignore param4, so we should not be breaking anything.
```
=> common: change unit of DO_REPOSITION yaw

message_definitions/v1.0/common.xml, message_definitions/v1.0/matrixpilot.xml, message_definitions/v1.0/storm32.xml
This is a subset of:
* #404 
This only includes the typos already fixed on mavlink/mavlink in:
* https://github.com/mavlink/mavlink/pull/2301
Once this is merged, we can discuss how we deal with:
```
message_definitions/v1.0/loweheiser.xml:41: miliseconds ==> milliseconds
message_definitions/v1.0/uAvionix.xml:152: reciever ==> receiver
```
=> Fix typos in XML files already made on mavlink/mavlink

message_definitions/v1.0/common.xml
Two commits which can be looked at independently
```
- makes as 1:1 with mavlink/mavlink
- removes some entries which we weren't using anyway
- deprecates the param-float capability in favour of two which allow the autopilot to specify how they pack the data into the message
- add some entries of dubious utility (eg. gripper, which could have been done with a GRIPPER_ACTION_GET_STATUS instead)
```
No changes required in ArduPilot for this - we didn't set any flags being removed, and the FLOAT thing is deprecated, not removed.
=> Bring AUTOPILOT_VERSION in-line with mavlink/mavlink

message_definitions/v1.0/loweheiser.xml, message_definitions/v1.0/uAvionix.xml
Related to:
* #401
* mavlink/mavlink#2301
* mavlink/mavlink#2311
```
./message_definitions/v1.0/loweheiser.xml:41: miliseconds ==> milliseconds
./message_definitions/v1.0/uAvionix.xml:152: reciever ==> receiver
```
=> Fix two typos in XML files

mavgenerate.py
Replicates upstream change:
* https://github.com/mavlink/mavlink/pull/2309
* https://github.com/mavlink/mavlink/pull/2303#pullrequestreview-3003545878
=> mavgenerate.py: Remove support for Python 2

.github/workflows/test_and_deploy.yml
Tighten up codespell based on the typo fixes in:
* #403
* #404
corresponds with upstream:
* mavlink/mavlink#2328
@tridge
=> Typos: codespell --ignore-words-list=dependees,ned

message_definitions/v1.0/common.xml
After discussion with @peterbarker on the Ardupilot discord, it has become clear that the Ardupilot ``RAW_IMU`` packet is identical to `SCALED_IMU`, yet `RAW_IMU `had no units documented. 
This PR introduces units that match what Ardupilot is sending into the `RAW_IMU `description. The edits were done via the GitHub web interface with no syntax checking for the XML, though I believe it remains correct.
I think it is worthy of note though that the way Ardupilot is using the `RAW_IMU `packet stands in direct conflict with (my interpretation) of the description of what the `RAW_IMU `packet is supposed to contain. Ardupilot `RAW_IMU `data is not raw, but processed and scaled to a known unit, the one of `SCALED_IMU`.
I'd argue discussion is warranted of whether Ardupilot should continue to …
=> Update common.xml to add units for RAW_IMU and clarify description
