ArduPilot/mavlink

- message_definitions/v1.0/ardupilotmega.xml
This is for (and blocks) Landing DEEP STALL PR https://github.com/ArduPilot/ardupilot/pull/5736
> Add PID_TUNING_LANDING enum

- message_definitions/v1.0/common.xml
Long pending doc updates to the RTCM flags. Sent here first for review, then we need to resync the ardupilot/mavlink repos again, as there is some divergence that has been happening.
> Common: Update the RTCM flags documentation

- message_definitions/v1.0/common.xml
Merge comits from the origin Mavlink repository into the ArduPilot fork
> Merge in changes from mavlink origin

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/uAvionix.xml
The GCS can then display this in a way that the user can understand and/or change each bit individualy.
> Added bitmasks

- examples/linux/README
- examples/linux/mavlink_udp.c
- mavgenerate.py
- message_definitions/v1.0/common.xml
These are from the upstream branch. After these the Ardupilot mavlink fork will be _mostly_ insync with upstream.
> Merge upstream changes

- message_definitions/v1.0/ardupilotmega.xml
This presents a deepstall status tracking message. Uses one of the last 21 ArduPilot specific messages.
> ArduPlane: Add deepstall status reporting

- message_definitions/v1.0/common.xml
I would like randy to fly AltiGator's DYDRA-12 drone. I am doing this support.
This drone is not a dodeca copter.
It is a dedeca hexa drone.
http://altigator.com/drone-onyxstar-hydra-uav/
> Add a rotor type for the dodeca rotor.

- message_definitions/v1.0/ardupilotmega.xml
For use with https://github.com/ArduPilot/ardupilot/pull/6341
~~I'm not sure why there are submodule changes... I need to double check that part, opening now for comments though.~~ EDIT: Fixed 
The values picked were the max integer values that can fit in a float correctly with 100% reliability. (Sticking with unsigned types minimized the changes in the accel cal lib)
> ArduPilot: Add success/failure states to accel cal reporting

- .travis.yml
- README.md
- doc/mavlink.php
- doc/mavlink_gitbook.py
- doc/mavlink_to_html_table.xsl
- doc/mavlink_to_html_table_gitbook.xsl
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/minimal.xml
This one should be added after #52 (done)
This requires https://github.com/ArduPilot/ardupilot/pull/7511
> Upstream updates part2

- message_definitions/v1.0/ardupilotmega.xml
Add a camera feedback event extension
> ArduPilot: Add camera feedback extension

- message_definitions/v1.0/common.xml
NFC. Corrected ArduPilot description and URL.  Will upstream if merged.
> [NFC] common.xml: update ArduPilot description. 

- doc/mavlink_gitbook.py
- doc/mavlink_to_html_table.xsl
- doc/mavlink_to_html_table_gitbook.xsl
- message_definitions/v1.0/ASLUAV.xml
- message_definitions/v1.0/common.xml
Another set of upstream changes
> Pr upstream changes 2

- message_definitions/v1.0/common.xml
The latest set of upstream mavlink changes
> Upstream mavlink changes

- message_definitions/v1.0/common.xml
allows for batteries to be reset on battery swap
> common.xml: added MAV_CMD_BATTERY_RESET

- message_definitions/v1.0/common.xml
this is useful for Vicon flight as an alternative to VISION_POSITION_ESTIMATE
> common: added GPS yaw to GPS_INPUT as an extension

- message_definitions/v1.0/ardupilotmega.xml
> ArduPilot: Add EFI_STATUS

- message_definitions/v1.0/ardupilotmega.xml
Added display="bitmask" to EKF_STATUS_REPORT flags field, as related enum values seem to be for a bitmask. Raised on mavlink mailing list and Hamish asked me to create a PR.
> Message Definitions ardupilotmega.xml

- message_definitions/v1.0/ardupilotmega.xml
This adds a new command for setting the distance to be repeated on mission resume. https://github.com/ArduPilot/ardupilot/pull/13208
> adupilotmega: add MAV_CMD_DO_SET_RESUME_REPEAT_DIST

- message_definitions/v1.0/common.xml
This adds a AIS message, this message is already in upstream MavLink.
https://github.com/ArduPilot/ardupilot/pull/13839
> common: add AIS message

- message_definitions/v1.0/ardupilotmega.xml
Adds label, units, enum, minValue and maxValue attributes to MAV_CMD parameters.
> ardupilotmega.xml: Add MAV_CMD parameters documentation (NFC)

- message_definitions/v1.0/ardupilotmega.xml
This PR superceeds https://github.com/ArduPilot/mavlink/pull/104 by tridge, and I believe answers all of Peter's concerns raised there.
> ardupilot: guided commands from RFDesign

- .travis.yml
- message_definitions/v1.0/common.xml
... I'll be creating a PR against mavlink upstream with proposed changes to this message.
> Add GENERATOR_STATUS message

- message_definitions/v1.0/ardupilotmega.xml
These are hard for a GCS to use if we don't maintain the list....
> Fix missing ArduPilot flight modes

- message_definitions/v1.0/common.xml
Some more useful things a generator might provide
> Add fields and flags to GENERATOR_STATUS

- message_definitions/v1.0/ardupilotmega.xml
This is used by https://github.com/ArduPilot/ardupilot/pull/14203 and https://github.com/ArduPilot/MAVProxy/pull/800
> Add support for OSD manipulation over mavlink

- message_definitions/v1.0/ardupilotmega.xml
Supports https://github.com/ArduPilot/ardupilot/pull/15358/files
I'll also update the pymavlink submodule on this PR once https://github.com/ArduPilot/pymavlink/pull/463 is merged.
> ardupilot: add THERMAL mode for ArduPlane.

- message_definitions/v1.0/common.xml
I plan on implementing this feature in ArduPilot, but need to add this new command to the Ardupilot's fork of mavlink.
> add command 260 for Oblique Survey camera trigger

- message_definitions/v1.0/all.xml
Cherry-picked from https://github.com/ArduPilot/mavlink/pull/151
these are straight-foward enough they can just be merged, I think.
> Cherry-Picked changes from upstream

- component_information/parameter.schema.json
- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/minimal.xml
I hope these are not very controversial :)
> Upstream up-to 2020-09-22 - non-controversial parts

- message_definitions/v1.0/common.xml
According to #151 this needs discussion
> Terrain protocol: add link to protocol docs (mavlink#1437)

- message_definitions/v1.0/common.xml
The required Ardupilot changes are in https://github.com/ArduPilot/ardupilot/pull/15404/commits/669e98bb6ba21d161036edca9bae7f5bfc43e026
and the CI tests pass
> BATTERY_STATUS.voltage_ext: add cells 10 to 14 (#1423)

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/minimal.xml
These are the ones that do need careful one-by-one discussion and testing
> Upstream up-to 2020-09-22

- message_definitions/v1.0/common.xml
I might have messed this up in a previous merge conflict resolution, sorry.
> common.xml: unfortunately RAW_RPM is still marked wip upstream :(

- message_definitions/v1.0/common.xml
Co-authored-by: Hamish Willee <hamishwillee@gmail.com>
@peterbarker complained that this needs a ArduPilot code change. But the code change has already been done in https://github.com/ArduPilot/ardupilot/pull/15404/commits/55676914512577ad33e93356bcc95a6b10c975a6 and the CI tests pass
> common: distance_sensor: add signal_quality field (mavlink#1403)

- message_definitions/v1.0/common.xml
@amilcarlucas @hamishwillee Thoughts?
> common.xml: add MAV_MOUNT_MODE_HOME_LOCATION to point at home

- message_definitions/v1.0/common.xml
Rename sysid to System ID for consistency with other messages
Add a couple of values to the CAMERA_CAP_FLAGS
> common.xml: minimize upstream diff

- message_definitions/v1.0/all.xml
Should fix pymavlink CI problem
> all.xml: stop building storm.xml until MDEF= problem is fixed

- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/common.xml
This way it can be globaly used.
> Move MAV_CMD_DO_SPRAYER from ardupilotmega.xml to common.xml

- message_definitions/v1.0/ardupilotmega.xml
Adds the units for angle_delta and tries to add clarity to the frame descriptions.
> ardupilotmega.xml: Vision_Position_Delta add unit to angle_delta and clarify frame descriptions

- message_definitions/v1.0/common.xml
Copies these missing extension fields into GPS2_RAW from GPS_RAW_INT
> common.xml: add extension fields from GPS_RAW_INT to GPS_RAW2

- message_definitions/v1.0/ardupilotmega.xml
This adds Auto RTL mode as in https://github.com/ArduPilot/ardupilot/pull/18075
> ardupilotmega: add COPTER_MODE_AUTO_RTL

- message_definitions/v1.0/ardupilotmega.xml
> ardupilot: added slew rate and PDmod for PID_TUNING

- message_definitions/v1.0/common.xml
common.xml: update hygrometer message
> common.xml: update hygrometer message

- message_definitions/v1.0/ardupilotmega.xml
Partner Request via Discord
This adds mount_mode to the MOUNT_STATUS message as an extension. 
Will send this for upstream MAVLINK merge once I get feedback.
> Add mount_mode to MOUNT_STATUS

- message_definitions/v1.0/common.xml
Adds the needed mavlink message changes and enum for this PR https://github.com/ArduPilot/ardupilot/pull/19742
> common.xml: add AUTOTUNE_AXIS from Upstream

- message_definitions/v1.0/all.xml
This reverts commit 8766b790a9d5ae7e50fa4cba5965d2560a288a24.
> Revert "all.xml: temporarily remove AVSUAS until we get namespace conflicts sorted"

- message_definitions/v1.0/ardupilotmega.xml
this goes along with recent addition of servo 17 to 32 support in ArduPilot
> ardupilot: added messages for ESC telem from 13 to 32

- message_definitions/v1.0/common.xml
Supply voltage to EFI sparking system.
> common.xml: add ignition_voltage to EFI_STATUS

- message_definitions/v1.0/common.xml
Pulls in the OpenDroneID messages from common
Opening this up is just for discussion....
And yes I kept the WIP tags since they are still tagged that in the upstream.
> Common: add OpenDroneID messages and enums

- message_definitions/v1.0/all.xml
- message_definitions/v1.0/ardupilotmega.xml
- message_definitions/v1.0/loweheiser.xml
It's not a great message set, but it is workable for this vendor.
> Add messages for Loweheiser generator

- message_definitions/v1.0/common.xml
Add options to `NAV_VTOL_LAND` to allow more control over how the approach is managed. Relates to https://github.com/ArduPilot/ardupilot/pull/14874
> Add NAV_VTOL_LAND options for the pattern

- message_definitions/v1.0/common.xml
> MAV_ODID_DESC_TYPE added ENUM messages 1 and 2

- message_definitions/v1.0/ardupilotmega.xml
see https://github.com/ArduPilot/ardupilot/issues/21584 for usage
> ardupilot: added SECURE_COMMAND messages

- message_definitions/v1.0/common.xml
MAVLink details associated with https://github.com/ArduPilot/ardupilot/pull/20541
> Support a return to default speed for DO_CHANGE_SPEED

- message_definitions/v1.0/common.xml
Change DO_LAND_START from 2D distance (lat, lng only) to 3D (also consider altitude).
> DO_LAND_START to consider altitude (3D distance)

- message_definitions/v1.0/common.xml
Prerequisite for [#23307](https://github.com/ArduPilot/ardupilot/pull/23307)
> common:Add GIMBAL_MANAGER_SET_ATTITUDE message from Upstream

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
needed for https://github.com/ArduPilot/pymavlink/pull/800
> fixed missing enums

- message_definitions/v1.0/common.xml
required for this issue [here](https://github.com/ArduPilot/ardupilot/issues/20985#:~:text=add%20GIMBAL_MANAGER_SET_PITCHYAW%20message%20support%20(not%20to%20be%20confused%20with%20MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW))
> common: Add message GIMBAL_MANAGER_SET_PITCHYAW from upstream

- message_definitions/v1.0/ardupilotmega.xml
for handling an external position estimate while dead reckoning
> ardupilot: added MAV_CMD_EXTERNAL_POSITION_ESTIMATE

- message_definitions/v1.0/common.xml
Equivalent for https://github.com/mavlink/mavlink/pull/2024
> common:  Add camera instance field to MAV_CMD_IMAGE_START/STOP_CAPTURE

- message_definitions/v1.0/ardupilotmega.xml
As per discussion in ArduPilot PR 27365 https://github.com/ArduPilot/ardupilot/pull/27365#issuecomment-2198767773
> ardupilotmega: add GUIDED HEADING_TYPE_DEFAULT

- message_definitions/v1.0/development.xml
From https://github.com/mavlink/mavlink/pull/1750, https://github.com/mavlink/mavlink/pull/1915 and  https://github.com/mavlink/mavlink/pull/1986
> Development: add required messages to support addition of modes at runtime

- message_definitions/v1.0/development.xml
these are supposed to be the shifted values, not the raw bit offsets!
> development.xml: correct AIRSPEED_SENSOR_FLAGS bitmask

- .github/workflows/test_and_deploy.yml
has some fixes for github CI we need
> pymavlink: update to master

- component_information/parameter.schema.json
> parameter.schema.json: Fix typos discovered by codespell

- .github/workflows/test_and_deploy.yml
- cmake/arkcmake/DefineCMakeDefaults.cmake
- doc/MAVLink2.md
- doc/mavlink.php
- doc/mavlink_gitbook.py
- examples/linux/mavlink_udp.c
Similar to upstream change:
* https://github.com/mavlink/mavlink/pull/2304
> Add codespell to GitHub Actions

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/standard.xml
From https://github.com/mavlink/mavlink/pull/2350
> GLOBAL_POSITION_INT - move from common to standard (#2350)

- message_definitions/v1.0/ardupilotmega.xml
ArduPilot hasn't sent this message for the last 3 years by default.
> ardupilotmega.xml: deprecate HWSTATUS

- message_definitions/v1.0/common.xml
Upstream PR is here: https://github.com/mavlink/mavlink/pull/2344 - please comment there rather than here.
> Add PARAM_ERROR message
